name: trading_advice_app_v2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  image_picker: ^0.8.4+4
  provider: ^6.0.0
  #amplify_flutter: ^0.2.9
  #amplify_auth_cognito: ^0.2.9
  cupertino_icons: ^1.0.6
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.5
  flutter_lints: ^3.0.0
  build_runner: ^2.1.7
  hive_generator: ^1.1.0
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  cloud_functions: ^5.0.0
  firebase_core_web: ^2.17.1
  flutter_svg: ^0.22.0
  flutterfire_cli: ^0.1.1+2
  firebase_storage: ^12.0.0
  image: ^3.0.1
  flutter_image_compress: ^1.1.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/beat.svg

fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Regular.ttf
      - asset: fonts/Roboto-Bold.ttf
        weight: 700

