// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpwQJviBmElIFldLP41mbCeByf-_ZRdFE',
    appId: '1:546409712378:web:71cf517c293ed7d0ad1743',
    messagingSenderId: '546409712378',
    projectId: 'dividendbeat',
    authDomain: 'dividendbeat.firebaseapp.com',
    storageBucket: 'dividendbeat.appspot.com',
    measurementId: 'G-M2PF1SD3HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'xxxxxxxx',
    appId: '1:546409712378:android:74ab0f8a229f9ceaad1743',
    messagingSenderId: '546409712378',
    projectId: 'dividendbeat',
    storageBucket: 'dividendbeat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'xxxxxxxxx',
    appId: '1:546409712378:ios:ac19a05e2f6c04d9ad1743',
    messagingSenderId: '546409712378',
    projectId: 'dividendbeat',
    storageBucket: 'dividendbeat.appspot.com',
    iosBundleId: 'com.example.dividendbro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'xxxxxxxxx',
    appId: '1:546409712378:ios:ac19a05e2f6c04d9ad1743',
    messagingSenderId: '546409712378',
    projectId: 'dividendbeat',
    storageBucket: 'dividendbeat.appspot.com',
    iosBundleId: 'com.example.dividendbro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'xxxxxxx',
    appId: '1:546409712378:web:5b850f1cdad88604ad1743',
    messagingSenderId: '546409712378',
    projectId: 'dividendbeat',
    authDomain: 'dividendbeat.firebaseapp.com',
    storageBucket: 'dividendbeat.appspot.com',
    measurementId: 'G-GG1Y91T16Y',
  );
}
